site_name: BlueCon
site_url: https://bluecon.afonsogarcia.dev/
repo_url: https://github.com/AfonsoFGarcia/bluecon

theme: 
  name: readthedocs
  include_homepage_in_sidebar: false
  prev_next_buttons_location: none
  collapse_navigation: false

nav:
  - Quickstart: quickstart.md

markdown_extensions:
  - toc:
      permalink: "#"