name: Publish Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    name: Publish Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
    - name: Copy README to index
      run: |
        rm docs/index.md
        cp README.md docs/index.md
    - name: Build docs
      run: python -m mkdocs build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: site/
  
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: docs
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2